### ISSUE TITLE
大佬可以方便打个release成品包吗

### ISSUE THREAD

**Issue by Familyye** [AlienwareHe/RDex#1]
**这个我编译老有问题  方便可以打个release成品包吗**

**Comment by AlienwareHe** [comment]
xposed的我没有测过，你可以帮我测一下哈哈，可以加我wx hx58929

**Comment by Familyye** [comment]
**某加密的脱出来还是存在大量odex指令  这边测试的是7.1.2     App是去年11.26加固的  不过大部分需要的代码还是被还原的**
